### ISSUE TITLE
Support loading SVG from string

### ISSUE THREAD

**Issue by doublex** [aslpavel/svgrasterize.py#1]
It is difficult to raster from string: `svg_scene_rec()` is not public
Anyway: awesome work

**Comment by aslpavel** [comment]
Thank you!

I've crated this project mostly to figure out how 2D rendering works, and as such I would not recommend to to use it any production code. I've shared this project mostly as a reference implementation using pure python, in the hope that it might help somebody learn how 2D rendering works.

Having said that I've added `svg_scene_from_str` which is capable of loading SVG file from string

**Comment by doublex** [comment]
`svgrasterize.py` is the only pure-python svg rasterizer I am aware of.
`svgrasterize.py` renders clockwise/counterclockwise path correctly.
Great code!
