### ISSUE TITLE
Has the issue with the anti aliasing algorithm been fixed yet?

### ISSUE THREAD

**Issue by Emasoft** [aslpavel/svgrasterize.py#4]
Has the issue with the anti aliasing algorithm been fixed yet? Or is it still being worked on?

**Comment by aslpavel** [comment]
You mean that coverage is computed multiple times? It is only an issue with weird path though. I do not think this package of a production quality of, and not particularly fast.

**Comment by Emasoft** [comment]
I found it very useful! You should improve it! 👍
